server:
  port: 0 #랜덤 포트
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: order-service # MSA 고유 아이디
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    show-sql: true

logging:
  level:
    me.study.orderservice: DEBUG

eureka:
  client:
    register-with-eureka: true # 현재 프로젝트 Discovery Service 등록(서버로서 기동만 되어 있으면 되기 때문에), Default true
    fetch-registry: true # EUREKA 서버로부터 인스턴스들의 정보를 주기적으로 가져올 것을 설정, Default true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    # 랜덤 포트로 0을 사용할 경우, 인스턴스 아이디가 겹치므로 커스텀 아이디 사용
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoint:
    web:
      exposure:
        include: refresh, health


